name: connectivity_plus
description: Flutter plugin for discovering the state of the network (WiFi & mobile/cellular) connectivity on Android and iOS.
version: 7.0.3
homepage: https://plus.fluttercommunity.dev/
repository: https://github.com/fluttercommunity/plus_plugins/tree/main/packages/
issue_tracker: https://github.com/fluttercommunity/plus_plugins/labels/connectivity_plus
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5"

flutter:
  plugin:
    platforms:
      android:
        package: dev.fluttercommunity.plus.connectivity
        pluginClass: ConnectivityPlugin

      ios:
        pluginClass: ConnectivityPlusPlugin

      web:
        default_package: connectivity_plus_web

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus_platform_interface:
     git:
       url: https://github.com/emirbashiri/connectivity_plus_platform_interface
       ref: main
  connectivity_plus_web:
     git:
       url: https://github.com/emirbashiri/connectivity_plus_web
       ref: main

  collection: ^1.16.0
  # connectivity_plus_web: ^1.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.21.1
  mockito: ^5.2.0
  plugin_platform_interface: ^2.1.2
  flutter_lints: ^2.0.1
